services:
  - type: web
    name: swapp-app
    env: python
    plan: free
    buildCommand: "./deploy.sh"
    startCommand: "gunicorn api.wsgi:app"
    numInstances: 1
    region: ohio
    envVars:
      - key: FLASK_APP
        value: api/app
      - key: FLASK_ENV
        value: production
      - key: FLASK_RUN_PORT
        value: 5000
      - key: FLASK_RUN_HOST
        value: 0.0.0.0
      - key: JWT_SECRET_KEY
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OAUTH_REDIRECT_URI
        value: false
      - key: FRONTEND_URL
        value: false
      - key: VITE_APP_NAME
        value: Swapp
      - key: VITE_BACKEND_URL
        value: https://swapp-app.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: swapp-db
          property: connectionString

databases:
    - name: swapp-db
      region: ohio
      ipAllowList: []
      plan: free
