services:
  - type: web
    name: swapp-app
    env: python
    plan: free
    region: ohio

    # Construcci√≥n (backend + frontend)
    buildCommand: |
      pip install -r requirements.txt
      cd front && npm install && npm run build

    # Inicio solo del BACKEND
    startCommand: "gunicorn api.app:app"

    # Variables de entorno
    envVars:
      - key: FLASK_APP
        value: api/app
      - key: FLASK_ENV
        value: production
      - key: FLASK_RUN_HOST
        value: 0.0.0.0
      - key: FLASK_RUN_PORT
        value: 5000
      - key: JWT_SECRET_KEY
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OAUTH_REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: VITE_BACKEND_URL
        sync: false
      - key: VITE_APP_NAME
        value: Swapp
      - key: DATABASE_URL
        fromDatabase:
          name: swapp-db
          property: connectionString

databases:
  - name: swapp-db
    region: ohio
    plan: free
