services:
  - type: web
    name: swapp-backend
    env: python
    plan: free
    buildCommand: "./deploy.sh"
    startCommand: "gunicorn api.wsgi:app"
    envVars:
      - key: FLASK_APP
        value: api/app
      - key: FLASK_ENV
        value: production
      - key: FLASK_RUN_PORT
        value: 5000
      - key: FLASK_RUN_HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: swapp-db
          property: connectionString
      - key: JWT_SECRET_KEY
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OAUTH_REDIRECT_URI
        sync: false
      - key: VITE_APP_NAME
        value: Swapp
      - key: VITE_BACKEND_URL
        value: https://swapp-backend.onrender.com

  - type: pserv
    name: swapp-db
    env: postgres
    plan: free
    disk:
      name: swapp-db-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 1